-- todo 테이블 초기화

DROP TABLE IF EXISTS todo;
CREATE TABLE todo (
	id 				BIGINT PRIMARY KEY AUTO_INCREMENT,
	description 	VARCHAR(100) NOT NULL,
	is_completed 	BOOLEAN DEFAULT FALSE,
	is_fixed 		BOOLEAN DEFAULT FALSE,
	created_at 		DATETIME DEFAULT CURRENT_TIMESTAMP,
	updated_at 		DATETIME DEFAULT CURRENT_TIMESTAMP,
	completed_at 	DATETIME DEFAULT NULL,
	is_deleted		BOOLEAN DEFAULT FALSE,
	deleted_at		DATETIME DEFAULT NULL
);